version: '3.8'

services:
  app:
    image: my-image:latest  # Use the tag specified in your GitHub Actions workflow
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"  # Adjust the ports based on your application's requirements
    environment:
      DATABASE_URL: postgres://exampleuser:examplepass@postgres:5432/exampledb
      REDIS_URL: redis://redis:6379

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
